# Generated by Django 5.1 on 2025-09-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_tag_uuid_alter_userpreferences_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='timezone',
            field=models.CharField(default='Africa/Kampala', help_text='IANA timezone string', max_length=50),
        ),
    ]
