# Generated by Django 5.2.4 on 2025-09-16 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_remove_temporaryuser_unique_temp_user_per_event_and_more'),
        ('users', '0005_userpreferences_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_generated_username',
            field=models.BooleanField(default=False, help_text='True if username was auto-generated'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_for_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_user_accounts', to='ticketing.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this temporary user expires', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_temporary',
            field=models.BooleanField(default=False, help_text='True if this is a temporary event-specific user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
