# Generated by Django 5.2.4 on 2025-10-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_temporary_user_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('Customer', 'Customer'), ('Sacco Admin', 'Sacco Admin'), ('Sacco Member', 'Sacco Member'), ('Sacco Secretary', 'Sacco Secretary')], default='Staff', max_length=30),
        ),
    ]
