# Generated by Django 5.2.4 on 2025-09-16 01:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_alter_eventmanager_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='temporaryuser',
            name='unique_temp_user_per_event',
        ),
        migrations.AddConstraint(
            model_name='temporaryuser',
            constraint=models.UniqueConstraint(fields=('username', 'event'), name='unique_temp_user_username_per_event'),
        ),
    ]
