# Generated by Django 5.2.4 on 2025-09-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    # This migration used to alter ProjectComment Meta options.
    # The ProjectComment model has since been removed; make this a no-op
    # to avoid state merge conflicts with 0002_delete_projectcomment.
    operations = []
