# Generated by Django 5.2.4 on 2025-09-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-updated_at', '-id']},
        ),
    ]
