# Generated by Django 5.2.4 on 2025-10-17 21:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaccoOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text='SACCO name', max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='SACCO-specific settings')),
                ('cash_round_amount', models.DecimalField(decimal_places=2, default=51000, help_text='Standard weekly contribution per member', max_digits=12)),
                ('meeting_day', models.CharField(default='Saturday', help_text='Day of the week for meetings', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_plan', models.CharField(default='basic', max_length=50)),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('admins', models.ManyToManyField(help_text='Users who can manage this SACCO', related_name='administered_saccos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SACCO Organization',
                'verbose_name_plural': 'SACCO Organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaccoMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('member_number', models.CharField(help_text='Unique within SACCO', max_length=50)),
                ('passbook_number', models.CharField(blank=True, max_length=50)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('alternative_phone', models.CharField(blank=True, max_length=20)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=255)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive'), ('resigned', 'Resigned')], default='active', max_length=20)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_left', models.DateField(blank=True, null=True)),
                ('is_secretary', models.BooleanField(default=False)),
                ('is_treasurer', models.BooleanField(default=False)),
                ('is_chairperson', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sacco_membership', to=settings.AUTH_USER_MODEL)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='saccos.saccoorganization')),
            ],
            options={
                'ordering': ['member_number'],
            },
        ),
        migrations.CreateModel(
            name='PassbookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text="e.g., 'Compulsory Savings'", max_length=100)),
                ('section_type', models.CharField(choices=[('savings', 'Savings'), ('welfare', 'Welfare'), ('development', 'Development'), ('loan', 'Loan'), ('emergency', 'Emergency'), ('interest', 'Interest'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_compulsory', models.BooleanField(default=False, help_text='Must contribute weekly')),
                ('weekly_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed weekly amount if compulsory', max_digits=12)),
                ('allow_variable_amounts', models.BooleanField(default=True, help_text='Allow members to contribute different amounts')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passbook_sections', to='saccos.saccoorganization')),
            ],
            options={
                'ordering': ['sacco', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MemberPassbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('passbook_number', models.CharField(max_length=50, unique=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passbook', to='saccos.saccomember')),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passbooks', to='saccos.saccoorganization')),
            ],
            options={
                'ordering': ['passbook_number'],
            },
        ),
        migrations.CreateModel(
            name='DeductionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applies_to', models.CharField(choices=[('recipient', 'Cash Round Recipient'), ('all_members', 'All Members'), ('specific', 'Specific Members')], default='recipient', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_rules', to='saccos.passbooksection')),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_rules', to='saccos.saccoorganization')),
            ],
            options={
                'ordering': ['sacco', 'section'],
            },
        ),
        migrations.CreateModel(
            name='PassbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Balance of this section after this entry', max_digits=12)),
                ('description', models.TextField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('week_number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_reversal', models.BooleanField(default=False)),
                ('passbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='saccos.memberpassbook')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_passbook_entries', to=settings.AUTH_USER_MODEL)),
                ('reverses_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='saccos.passbookentry')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='saccos.passbooksection')),
            ],
            options={
                'verbose_name_plural': 'Passbook Entries',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['passbook', 'section'], name='saccos_pass_passboo_36582f_idx'), models.Index(fields=['transaction_date'], name='saccos_pass_transac_8c789e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='saccomember',
            index=models.Index(fields=['sacco', 'status'], name='saccos_sacc_sacco_i_5ae3c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saccomember',
            unique_together={('sacco', 'member_number')},
        ),
        migrations.AlterUniqueTogether(
            name='passbooksection',
            unique_together={('sacco', 'name')},
        ),
    ]
