# Generated by Django 5.2.4 on 2025-10-19 21:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_account_scope_alter_transaction_category'),
        ('saccos', '0004_passbookentry_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaccoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('account', models.OneToOneField(help_text='Link to the finance Account model', on_delete=django.db.models.deletion.PROTECT, related_name='sacco_link', to='finance.account')),
                ('sacco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sacco_account', to='saccos.saccoorganization')),
            ],
            options={
                'verbose_name': 'SACCO Account',
                'verbose_name_plural': 'SACCO Accounts',
            },
        ),
    ]
