# Generated by Django 5.2.4 on 2025-10-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccos', '0005_saccoaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saccomember',
            name='savings_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Member's personal savings goal", max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='saccomember',
            name='savings_goal_deadline',
            field=models.DateField(blank=True, help_text='Target date to reach savings goal', null=True),
        ),
    ]
