# Generated by Django 5.2.4 on 2025-10-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccos', '0006_saccomember_savings_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saccomember',
            name='role',
            field=models.CharField(blank=True, help_text="Member's role (Chairperson, Secretary, Treasurer, Committee Member, etc.)", max_length=50),
        ),
    ]
