# Generated by Django 5.2.4 on 2025-10-21 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccos', '0007_saccomember_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashroundschedule',
            name='sacco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_round_schedules', to='saccos.saccoorganization'),
        ),
        migrations.AlterField(
            model_name='cashroundschedule',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklymeeting',
            name='week_number',
            field=models.PositiveIntegerField(help_text='Week number in cash round cycle'),
        ),
        migrations.CreateModel(
            name='CashRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text='e.g., Round 1 - January 2025', max_length=200)),
                ('round_number', models.PositiveIntegerField(help_text='Auto-increment per SACCO')),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField(help_text='Auto-calc: start + (num_members * weeks)')),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('weekly_amount', models.DecimalField(decimal_places=2, help_text='How much each member pays per week', max_digits=12)),
                ('num_weeks', models.PositiveIntegerField(help_text='Usually = number of members')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_rounds', to=settings.AUTH_USER_MODEL)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_rounds', to='saccos.saccoorganization')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='cashroundschedule',
            name='cash_round',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='saccos.cashround'),
        ),
        migrations.AddField(
            model_name='weeklymeeting',
            name='cash_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='saccos.cashround'),
        ),
        migrations.CreateModel(
            name='CashRoundMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('position_in_rotation', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('cash_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_members', to='saccos.cashround')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_rounds', to='saccos.saccomember')),
            ],
            options={
                'ordering': ['position_in_rotation'],
            },
        ),
        migrations.AddIndex(
            model_name='cashround',
            index=models.Index(fields=['sacco', 'status'], name='saccos_cash_sacco_i_708df4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cashround',
            unique_together={('sacco', 'round_number')},
        ),
        migrations.AddIndex(
            model_name='cashroundmember',
            index=models.Index(fields=['cash_round', 'is_active'], name='saccos_cash_cash_ro_2f9a97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cashroundmember',
            unique_together={('cash_round', 'member')},
        ),
    ]
