# Generated by Django 5.2.4 on 2025-10-21 17:14

from django.db import migrations
from datetime import timedelta


def migrate_existing_schedules(apps, schema_editor):
    """
    Migrate existing CashRoundSchedule records to new CashRound model
    """
    CashRoundSchedule = apps.get_model('saccos', 'CashRoundSchedule')
    CashRound = apps.get_model('saccos', 'CashRound')
    CashRoundMember = apps.get_model('saccos', 'CashRoundMember')
    SaccoOrganization = apps.get_model('saccos', 'SaccoOrganization')
    
    # Get all existing schedules
    for schedule in CashRoundSchedule.objects.all():
        if schedule.cash_round_id:
            # Already migrated, skip
            continue
            
        # Get or calculate round number for this SACCO
        sacco = schedule.sacco
        existing_rounds_count = CashRound.objects.filter(sacco=sacco).count()
        round_number = existing_rounds_count + 1
        
        # Determine status based on is_active and dates
        if schedule.is_active:
            status = 'active'
        elif schedule.end_date:
            status = 'completed'
        else:
            status = 'active'  # Default to active if no end date
        
        # Calculate expected end date
        num_members = len(schedule.rotation_order) if schedule.rotation_order else 0
        expected_end_date = schedule.start_date + timedelta(weeks=num_members) if schedule.start_date and num_members > 0 else schedule.start_date
        
        # Create CashRound for this schedule
        cash_round = CashRound.objects.create(
            sacco=sacco,
            name=f"Migrated Round {round_number} - {schedule.start_date.strftime('%B %Y') if schedule.start_date else 'Unknown'}",
            round_number=round_number,
            start_date=schedule.start_date or sacco.created_at.date(),
            expected_end_date=expected_end_date or sacco.created_at.date(),
            actual_end_date=schedule.end_date,
            weekly_amount=sacco.cash_round_amount,  # Use SACCO's default
            num_weeks=num_members,
            status=status,
            created_by=None,  # No user tracked in old model
            started_at=schedule.created_at if status == 'active' else None,
            completed_at=schedule.updated_at if status == 'completed' else None,
            notes=f"Migrated from CashRoundSchedule ID: {schedule.id}"
        )
        
        # Create CashRoundMember records for each member in rotation
        for position, member_id in enumerate(schedule.rotation_order or []):
            try:
                CashRoundMember.objects.create(
                    cash_round=cash_round,
                    member_id=member_id,
                    position_in_rotation=position,
                    is_active=schedule.is_active
                )
            except Exception as e:
                # Skip if member doesn't exist or duplicate
                print(f"Warning: Could not create CashRoundMember for member {member_id}: {e}")
                continue
        
        # Link the schedule to the cash round
        schedule.cash_round = cash_round
        schedule.save()
        
        print(f"Migrated schedule {schedule.id} to CashRound {cash_round.id}: {cash_round.name}")


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration - unlink cash rounds from schedules
    """
    CashRoundSchedule = apps.get_model('saccos', 'CashRoundSchedule')
    
    # Simply unlink - don't delete CashRound records in case they're being used
    CashRoundSchedule.objects.update(cash_round=None)


class Migration(migrations.Migration):

    dependencies = [
        ('saccos', '0008_alter_cashroundschedule_sacco_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_schedules, reverse_migration),
    ]
