# Generated by Django 5.2.4 on 2025-10-21 17:14

from django.db import migrations


def link_meetings_to_cash_rounds(apps, schema_editor):
    """
    Link existing WeeklyMeeting records to CashRound based on date ranges
    """
    WeeklyMeeting = apps.get_model('saccos', 'WeeklyMeeting')
    CashRound = apps.get_model('saccos', 'CashRound')
    
    # Get all meetings that don't have a cash_round yet
    for meeting in WeeklyMeeting.objects.filter(cash_round__isnull=True):
        # Find the appropriate cash round for this meeting
        # Match by SACCO and date range
        cash_round = CashRound.objects.filter(
            sacco=meeting.sacco,
            start_date__lte=meeting.meeting_date,
            status__in=['active', 'completed']
        ).order_by('-start_date').first()
        
        if cash_round:
            meeting.cash_round = cash_round
            meeting.save()
            print(f"Linked meeting {meeting.id} ({meeting.meeting_date}) to cash round {cash_round.id}")
        else:
            # No cash round found - could be before any cash round was created
            # Try to find any active cash round for this SACCO
            cash_round = CashRound.objects.filter(
                sacco=meeting.sacco,
                status='active'
            ).first()
            
            if cash_round:
                meeting.cash_round = cash_round
                meeting.save()
                print(f"Linked meeting {meeting.id} to default active cash round {cash_round.id}")
            else:
                print(f"Warning: No cash round found for meeting {meeting.id} on {meeting.meeting_date}")


def reverse_link_meetings(apps, schema_editor):
    """
    Reverse the linking - unlink meetings from cash rounds
    """
    WeeklyMeeting = apps.get_model('saccos', 'WeeklyMeeting')
    
    # Unlink all meetings
    WeeklyMeeting.objects.update(cash_round=None)


class Migration(migrations.Migration):

    dependencies = [
        ('saccos', '0009_migrate_cash_round_data'),
    ]

    operations = [
        migrations.RunPython(link_meetings_to_cash_rounds, reverse_link_meetings),
    ]
