# Generated by Django 5.2.4 on 2025-10-21 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccos', '0010_link_meetings_to_cash_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductionrule',
            name='cash_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deduction_rules', to='saccos.cashround'),
        ),
        migrations.AlterField(
            model_name='deductionrule',
            name='sacco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deduction_rules', to='saccos.saccoorganization'),
        ),
    ]
