# Generated by Django 5.2.4 on 2025-10-21 18:42

from django.db import migrations


def link_deduction_rules_to_cash_rounds(apps, schema_editor):
    """
    Link existing deduction rules to cash rounds.
    Each SACCO's deduction rules will be linked to their active cash round.
    If no active round exists, link to the most recent round.
    """
    DeductionRule = apps.get_model('saccos', 'DeductionRule')
    CashRound = apps.get_model('saccos', 'CashRound')
    
    for rule in DeductionRule.objects.filter(cash_round__isnull=True):
        if not rule.sacco:
            print(f"Warning: DeductionRule {rule.id} has no SACCO, skipping...")
            continue
        
        # Try to find an active cash round for this SACCO
        cash_round = CashRound.objects.filter(
            sacco=rule.sacco,
            status='active'
        ).first()
        
        # If no active round, get the most recent one
        if not cash_round:
            cash_round = CashRound.objects.filter(
                sacco=rule.sacco
            ).order_by('-start_date').first()
        
        if cash_round:
            rule.cash_round = cash_round
            rule.save()
            print(f"Linked DeductionRule {rule.id} to CashRound {cash_round.id}")
        else:
            print(f"Warning: No cash round found for SACCO {rule.sacco.name}, DeductionRule {rule.id} not linked")


def reverse_link_deduction_rules(apps, schema_editor):
    """
    Reverse the linking - unlink deduction rules from cash rounds
    """
    DeductionRule = apps.get_model('saccos', 'DeductionRule')
    
    # Simply unlink - keep the sacco reference
    DeductionRule.objects.update(cash_round=None)


class Migration(migrations.Migration):

    dependencies = [
        ('saccos', '0011_deductionrule_cash_round_alter_deductionrule_sacco'),
    ]

    operations = [
        migrations.RunPython(link_deduction_rules_to_cash_rounds, reverse_link_deduction_rules),
    ]
