# Generated by Django 5.2.4 on 2025-11-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccos', '0012_link_deduction_rules_to_cash_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='saccoloan',
            name='repayment_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly')], default='monthly', help_text='Repayment frequency (monthly or weekly)', max_length=10),
        ),
    ]
