# Generated by Django 5.2.4 on 2025-12-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccos', '0013_saccoloan_repayment_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='saccoloan',
            name='loan_type',
            field=models.CharField(choices=[('regular', 'Regular Loan'), ('emergency', 'Emergency Support'), ('missed_contribution', 'Missed Contribution')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklycontribution',
            name='funding_source',
            field=models.CharField(choices=[('member', 'Paid by Member'), ('sacco', 'Covered by SACCO (Defaulted)')], default='member', help_text='Who actually provided this contribution', max_length=20),
        ),
    ]
