 # Generated by Django 5.2.4 on 2025-12-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccos', '0014_saccoloan_loan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passbooksection',
            name='withdrawable',
            field=models.BooleanField(default=False, help_text='If true, balances in this section can be withdrawn by members'),
        ),
    ]
