# Generated by Django 5.2.4 on 2025-12-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saccos', '0016_withdrawals'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='saccowithdrawal',
            new_name='saccos_sacc_sacco_i_068f3a_idx',
            old_name='saccos_withdr_sacco_status_idx',
        ),
        migrations.RenameIndex(
            model_name='saccowithdrawal',
            new_name='saccos_sacc_member__c32ffb_idx',
            old_name='saccos_withdr_member_status_idx',
        ),
    ]
