# Generated by Django 5.2.4 on 2025-09-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_invoice_options_remove_invoice_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
    ]
