# Generated by Django 5.2.4 on 2025-09-12 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_personalbudget_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='personaldebt',
            constraint=models.CheckConstraint(condition=models.Q(('creditor_name__isnull', False), models.Q(('creditor_name', ''), _negated=True)), name='debt_creditor_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='personaldebt',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('borrowed_date'))), name='debt_due_date_after_borrowed_date'),
        ),
    ]
