# Generated by Django 5.2.4 on 2025-09-25 03:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_companyrecurringtransaction_companysavingsgoal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='calculated_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated from items', max_digits=12),
        ),
        migrations.AddField(
            model_name='requisition',
            name='has_items',
            field=models.BooleanField(default=False, help_text='True if requisition uses itemized breakdown'),
        ),
        migrations.CreateModel(
            name='RequisitionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file', models.FileField(upload_to='requisitions/documents/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='finance.requisition')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('particular', models.CharField(help_text='Item description', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.requisition')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
