# Generated by Django 5.2.4 on 2025-09-29 15:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_add_requisition_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtpayment',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Portion of the payment applied to interest', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Portion of the payment applied to principal', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Portion of the repayment recognised as interest', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Portion of the repayment applied to principal', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='personalaccounttransfer',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount credited to the destination account after applying exchange rate', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='personaltransaction',
            name='affects_profit',
            field=models.BooleanField(default=True, help_text='If false, exclude from income/expense reporting while still impacting cash balances'),
        ),
        migrations.AlterField(
            model_name='companybudget',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('shopping', 'Shopping'), ('education', 'Education'), ('savings', 'Savings & Investment'), ('debt', 'Debt Payment'), ('rent', 'Rent & Housing'), ('insurance', 'Insurance'), ('subscriptions', 'Subscriptions'), ('gifts', 'Gifts & Donations'), ('transfer', 'Account Transfer'), ('transfer_fee', 'Transfer Fee'), ('loan_given', 'Loan Given'), ('debt_interest', 'Debt Interest'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='companyrecurringtransaction',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('shopping', 'Shopping'), ('education', 'Education'), ('savings', 'Savings & Investment'), ('debt', 'Debt Payment'), ('rent', 'Rent & Housing'), ('insurance', 'Insurance'), ('subscriptions', 'Subscriptions'), ('gifts', 'Gifts & Donations'), ('transfer', 'Account Transfer'), ('transfer_fee', 'Transfer Fee'), ('loan_given', 'Loan Given'), ('debt_interest', 'Debt Interest'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personalbudget',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('shopping', 'Shopping'), ('education', 'Education'), ('savings', 'Savings & Investment'), ('debt', 'Debt Payment'), ('rent', 'Rent & Housing'), ('insurance', 'Insurance'), ('subscriptions', 'Subscriptions'), ('gifts', 'Gifts & Donations'), ('transfer', 'Account Transfer'), ('transfer_fee', 'Transfer Fee'), ('loan_given', 'Loan Given'), ('debt_interest', 'Debt Interest'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personaltransaction',
            name='expense_category',
            field=models.CharField(blank=True, choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('shopping', 'Shopping'), ('education', 'Education'), ('savings', 'Savings & Investment'), ('debt', 'Debt Payment'), ('rent', 'Rent & Housing'), ('insurance', 'Insurance'), ('subscriptions', 'Subscriptions'), ('gifts', 'Gifts & Donations'), ('transfer', 'Account Transfer'), ('transfer_fee', 'Transfer Fee'), ('loan_given', 'Loan Given'), ('debt_interest', 'Debt Interest'), ('other', 'Other')], help_text='Required for expense transactions', max_length=50),
        ),
        migrations.AlterField(
            model_name='personaltransaction',
            name='income_source',
            field=models.CharField(blank=True, choices=[('salary', 'Salary'), ('freelance', 'Freelance Work'), ('business', 'Business Income'), ('investment', 'Investment Returns'), ('rental', 'Rental Income'), ('gift', 'Gift/Allowance'), ('refund', 'Refund'), ('bonus', 'Bonus'), ('transfer', 'Account Transfer'), ('loan_repayment', 'Loan Repayment'), ('loan_interest', 'Loan Interest'), ('other', 'Other')], help_text='Required for income transactions', max_length=50),
        ),
        migrations.AlterField(
            model_name='personaltransactionrecurring',
            name='expense_category',
            field=models.CharField(blank=True, choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('shopping', 'Shopping'), ('education', 'Education'), ('savings', 'Savings & Investment'), ('debt', 'Debt Payment'), ('rent', 'Rent & Housing'), ('insurance', 'Insurance'), ('subscriptions', 'Subscriptions'), ('gifts', 'Gifts & Donations'), ('transfer', 'Account Transfer'), ('transfer_fee', 'Transfer Fee'), ('loan_given', 'Loan Given'), ('debt_interest', 'Debt Interest'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personaltransactionrecurring',
            name='income_source',
            field=models.CharField(blank=True, choices=[('salary', 'Salary'), ('freelance', 'Freelance Work'), ('business', 'Business Income'), ('investment', 'Investment Returns'), ('rental', 'Rental Income'), ('gift', 'Gift/Allowance'), ('refund', 'Refund'), ('bonus', 'Bonus'), ('transfer', 'Account Transfer'), ('loan_repayment', 'Loan Repayment'), ('loan_interest', 'Loan Interest'), ('other', 'Other')], max_length=50),
        ),
    ]
