# Generated by Django 5.2.4 on 2025-09-29 17:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_debtpayment_interest_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltransaction',
            name='goal_applied_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='personaltransaction',
            name='goal_applied_direction',
            field=models.CharField(blank=True, choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='personaltransaction',
            name='invoice_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_transaction', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='personaltransaction',
            name='linked_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.personalbudget'),
        ),
        migrations.AddField(
            model_name='personaltransaction',
            name='linked_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.personalsavingsgoal'),
        ),
        migrations.AddField(
            model_name='personaltransaction',
            name='linked_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_transactions', to='finance.invoice'),
        ),
        migrations.AlterField(
            model_name='companybudget',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('shopping', 'Shopping'), ('education', 'Education'), ('savings', 'Savings & Investment'), ('debt', 'Debt Payment'), ('rent', 'Rent & Housing'), ('insurance', 'Insurance'), ('subscriptions', 'Subscriptions'), ('gifts', 'Gifts & Donations'), ('transfer', 'Account Transfer'), ('transfer_fee', 'Transfer Fee'), ('loan_given', 'Loan Given'), ('debt_interest', 'Debt Interest'), ('other', 'Other'), ('donation', 'Donations/Gifts'), ('owner_draw', 'Owner Draw')], max_length=50),
        ),
        migrations.AlterField(
            model_name='companyrecurringtransaction',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('shopping', 'Shopping'), ('education', 'Education'), ('savings', 'Savings & Investment'), ('debt', 'Debt Payment'), ('rent', 'Rent & Housing'), ('insurance', 'Insurance'), ('subscriptions', 'Subscriptions'), ('gifts', 'Gifts & Donations'), ('transfer', 'Account Transfer'), ('transfer_fee', 'Transfer Fee'), ('loan_given', 'Loan Given'), ('debt_interest', 'Debt Interest'), ('other', 'Other'), ('donation', 'Donations/Gifts'), ('owner_draw', 'Owner Draw')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personalbudget',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('shopping', 'Shopping'), ('education', 'Education'), ('savings', 'Savings & Investment'), ('debt', 'Debt Payment'), ('rent', 'Rent & Housing'), ('insurance', 'Insurance'), ('subscriptions', 'Subscriptions'), ('gifts', 'Gifts & Donations'), ('transfer', 'Account Transfer'), ('transfer_fee', 'Transfer Fee'), ('loan_given', 'Loan Given'), ('debt_interest', 'Debt Interest'), ('other', 'Other'), ('donation', 'Donations/Gifts'), ('owner_draw', 'Owner Draw')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personaltransaction',
            name='expense_category',
            field=models.CharField(blank=True, choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('shopping', 'Shopping'), ('education', 'Education'), ('savings', 'Savings & Investment'), ('debt', 'Debt Payment'), ('rent', 'Rent & Housing'), ('insurance', 'Insurance'), ('subscriptions', 'Subscriptions'), ('gifts', 'Gifts & Donations'), ('transfer', 'Account Transfer'), ('transfer_fee', 'Transfer Fee'), ('loan_given', 'Loan Given'), ('debt_interest', 'Debt Interest'), ('other', 'Other'), ('donation', 'Donations/Gifts'), ('owner_draw', 'Owner Draw')], help_text='Required for expense transactions', max_length=50),
        ),
        migrations.AlterField(
            model_name='personaltransaction',
            name='income_source',
            field=models.CharField(blank=True, choices=[('salary', 'Salary'), ('freelance', 'Freelance Work'), ('business', 'Business Income'), ('investment', 'Investment Returns'), ('rental', 'Rental Income'), ('gift', 'Gift/Allowance'), ('refund', 'Refund'), ('bonus', 'Bonus'), ('transfer', 'Account Transfer'), ('loan_repayment', 'Loan Repayment'), ('loan_interest', 'Loan Interest'), ('donation', 'Donation'), ('sponsorship', 'Sponsorship'), ('owner_contribution', 'Owner Contribution'), ('other', 'Other')], help_text='Required for income transactions', max_length=50),
        ),
        migrations.AlterField(
            model_name='personaltransactionrecurring',
            name='expense_category',
            field=models.CharField(blank=True, choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('shopping', 'Shopping'), ('education', 'Education'), ('savings', 'Savings & Investment'), ('debt', 'Debt Payment'), ('rent', 'Rent & Housing'), ('insurance', 'Insurance'), ('subscriptions', 'Subscriptions'), ('gifts', 'Gifts & Donations'), ('transfer', 'Account Transfer'), ('transfer_fee', 'Transfer Fee'), ('loan_given', 'Loan Given'), ('debt_interest', 'Debt Interest'), ('other', 'Other'), ('donation', 'Donations/Gifts'), ('owner_draw', 'Owner Draw')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personaltransactionrecurring',
            name='income_source',
            field=models.CharField(blank=True, choices=[('salary', 'Salary'), ('freelance', 'Freelance Work'), ('business', 'Business Income'), ('investment', 'Investment Returns'), ('rental', 'Rental Income'), ('gift', 'Gift/Allowance'), ('refund', 'Refund'), ('bonus', 'Bonus'), ('transfer', 'Account Transfer'), ('loan_repayment', 'Loan Repayment'), ('loan_interest', 'Loan Interest'), ('donation', 'Donation'), ('sponsorship', 'Sponsorship'), ('owner_contribution', 'Owner Contribution'), ('other', 'Other')], max_length=50),
        ),
    ]
