# Generated by Django 5.2.4 on 2025-10-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_personaltransaction_goal_applied_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('app_dev', 'App Development'), ('training', 'Training'), ('facilitation', 'Facilitation'), ('travel', 'Travel'), ('marketing', 'Marketing'), ('salary', 'Salary'), ('infrastructure', 'Infrastructure'), ('operations', 'Operations'), ('utilities', 'Utilities'), ('office', 'Office Supplies'), ('tax', 'Tax'), ('invoice', 'Invoice Payment'), ('miscellaneous', 'Miscellaneous')], max_length=50),
        ),
    ]
