# Generated by Django 5.2.4 on 2025-10-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='scope',
            field=models.CharField(choices=[('company', 'Company'), ('personal', 'Personal'), ('sacco', 'SACCO')], default='company', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('app_dev', 'App Development'), ('training', 'Training'), ('facilitation', 'Facilitation'), ('travel', 'Travel'), ('marketing', 'Marketing'), ('salary', 'Salary'), ('infrastructure', 'Infrastructure'), ('operations', 'Operations'), ('utilities', 'Utilities'), ('office', 'Office Supplies'), ('tax', 'Tax'), ('invoice', 'Invoice Payment'), ('miscellaneous', 'Miscellaneous'), ('sacco_savings', 'SACCO Savings'), ('sacco_loan_disbursement', 'SACCO Loan Disbursement'), ('sacco_loan_repayment', 'SACCO Loan Repayment'), ('sacco_welfare', 'SACCO Welfare'), ('sacco_development', 'SACCO Development'), ('sacco_emergency', 'SACCO Emergency Support')], max_length=50),
        ),
    ]
