# Generated by Django 5.2.4 on 2025-12-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_transaction_transaction_charge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ('-date', '-created_at')},
        ),
    ]
