# Generated by Django 5.2.4 on 2025-12-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_alter_receipt_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('app_dev', 'App Development'), ('training', 'Training'), ('facilitation', 'Facilitation'), ('travel', 'Travel'), ('marketing', 'Marketing'), ('salary', 'Salary'), ('infrastructure', 'Infrastructure'), ('operations', 'Operations'), ('utilities', 'Utilities'), ('office', 'Office Supplies'), ('tax', 'Tax'), ('invoice', 'Invoice Payment'), ('miscellaneous', 'Miscellaneous'), ('sacco_savings', 'SACCO Savings'), ('sacco_loan_disbursement', 'SACCO Loan Disbursement'), ('sacco_loan_repayment', 'SACCO Loan Repayment'), ('sacco_welfare', 'SACCO Welfare'), ('sacco_development', 'SACCO Development'), ('sacco_emergency', 'SACCO Emergency Support'), ('sacco_withdrawal', 'SACCO Withdrawal')], max_length=50),
        ),
    ]
