# Generated by Django 5.2.4 on 2025-08-03 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_staffrole_staffprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message_sent', models.TextField()),
                ('response_text', models.TextField()),
                ('used_gpt', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffrole')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fallback_text', models.TextField()),
                ('condition', models.CharField(blank=True, help_text='Optional keyword trigger or state', max_length=255)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_responses', to='accounts.staffrole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VACommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('trigger_text', models.CharField(help_text='User command text', max_length=255)),
                ('match_type', models.CharField(choices=[('exact', 'Exact'), ('contains', 'Contains')], default='exact', max_length=20)),
                ('response_mode', models.CharField(choices=[('text', 'Text'), ('api', 'API')], default='text', max_length=20)),
                ('response_text', models.TextField(blank=True, help_text='Fallback reply if text mode')),
                ('api_endpoint', models.CharField(blank=True, help_text='API path to call if response_mode=api', max_length=255)),
                ('requires_auth', models.BooleanField(default=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='accounts.staffrole')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
