# Generated by Django 5.2.4 on 2025-09-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_co_content_7dda54_idx',
            old_name='comments_co_content_25e7a3_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_co_author__a235af_idx',
            old_name='comments_co_author__39e7e4_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_co_created_5f6a12_idx',
            old_name='comments_co_created_2b2f49_idx',
        ),
    ]
