# Generated by Django 5.2.4 on 2025-10-18 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0014_alter_account_scope_alter_transaction_category'),
        ('saccos', '0003_subscriptionplan_saccosubscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaccoEnterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('retail', 'Retail Shop'), ('wholesale', 'Wholesale'), ('restaurant', 'Restaurant/Café'), ('farm', 'Agriculture'), ('transport', 'Transport Service'), ('manufacturing', 'Manufacturing'), ('services', 'Services'), ('other', 'Other')], default='retail', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('finance_account', models.ForeignKey(blank=True, help_text='Main operating account for this business', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enterprises', to='finance.account')),
                ('managed_by', models.ManyToManyField(blank=True, related_name='managed_enterprises', to=settings.AUTH_USER_MODEL)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprises', to='saccos.saccoorganization')),
            ],
            options={
                'verbose_name': 'SACCO Enterprise',
                'verbose_name_plural': 'SACCO Enterprises',
                'db_table': 'businesses_enterprise',
                'ordering': ['-created_at'],
                'unique_together': {('sacco', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EnterpriseConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('stock_management_enabled', models.BooleanField(default=False, help_text='Enable inventory/stock tracking')),
                ('sales_management_enabled', models.BooleanField(default=False, help_text='Enable sales/POS features')),
                ('auto_create_finance_entries', models.BooleanField(default=True, help_text='Automatically create finance transactions for business activities')),
                ('sales_affect_stock', models.BooleanField(default=True, help_text='Sales automatically reduce stock (requires both stock and sales modules)')),
                ('default_currency', models.CharField(default='UGX', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Default tax rate percentage', max_digits=5)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Additional configuration as JSON')),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='businesses.saccoenterprise')),
            ],
            options={
                'verbose_name': 'Enterprise Configuration',
                'verbose_name_plural': 'Enterprise Configurations',
                'db_table': 'businesses_configuration',
            },
        ),
    ]
