# Generated by Django 5.2.4 on 2025-10-18 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_stockitem_stockmovement_and_more'),
        ('finance', '0014_alter_account_scope_alter_transaction_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sale_number', models.CharField(help_text='Auto-generated unique sale number', max_length=50, unique=True)),
                ('sale_date', models.DateField()),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all line items before tax/discount', max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total tax amount', max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total discount', max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Final amount after tax and discount', max_digits=15)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile', 'Mobile Money'), ('bank', 'Bank Transfer'), ('credit', 'Credit')], default='cash', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount received from customer', max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='businesses.saccoenterprise')),
                ('finance_transaction', models.ForeignKey(blank=True, help_text='Linked finance transaction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_sales', to='finance.transaction')),
                ('served_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'businesses_sale',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('quantity', models.IntegerField(help_text='Quantity sold')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit', max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit (for profit calculation)', max_digits=15)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage', max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount amount', max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax rate percentage', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='quantity × unit_price', max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, help_text='Final amount after discount and tax', max_digits=15)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='businesses.sale')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='businesses.stockitem')),
            ],
            options={
                'db_table': 'businesses_sale_item',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['enterprise', 'sale_date'], name='businesses__enterpr_532cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['enterprise', 'status'], name='businesses__enterpr_c480bb_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='businesses__sale_da_f093a3_idx'),
        ),
    ]
