# Generated by Django 5.2.4 on 2025-10-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_sale_saleitem_sale_businesses__enterpr_532cd6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit (what we pay)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling price per unit', max_digits=15, null=True),
        ),
    ]
