# Generated by Django 5.2.4 on 2025-10-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_alter_stockitem_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Quantity sold', null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='quantity × unit_price', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Final amount after discount and tax', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Cost per unit (for profit calculation)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling price per unit', max_digits=15, null=True),
        ),
    ]
