# Generated by Django 5.2.4 on 2025-10-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_alter_saleitem_quantity_alter_saleitem_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock keeping unit - unique identifier', max_length=50),
        ),
    ]
