# Generated by Django 5.2.4 on 2025-10-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_alter_stockitem_sku'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['enterprise', 'sku'], name='businesses__enterpr_7898e5_idx'),
        ),
    ]
