# Generated by Django 5.2.4 on 2025-11-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_alter_stockitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='pack_cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of entire pack/crate (e.g., 10,000 for crate of 12 sodas)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='pack_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling price for whole pack (leave blank if selling by unit only)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='pack_size',
            field=models.IntegerField(blank=True, help_text='Number of units in a pack/crate/carton (e.g., 12 for a crate of sodas)', null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit (only for items bought individually, NOT for pack items)', max_digits=15, null=True),
        ),
    ]
