# Generated by Django 5.1 on 2025-09-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
    ]
