# Generated by Django 5.2.4 on 2025-08-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffrole_staffprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='name',
            field=models.CharField(blank=True, help_text='Only used for virtual assistants or aliases', max_length=255),
        ),
    ]
