# Generated by Django 5.2.4 on 2025-08-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_staffprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
