# Generated by Django 5.2.4 on 2025-08-07 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_referral_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffrole',
            options={'ordering': ['id']},
        ),
    ]
