# Generated by Django 5.2.4 on 2025-09-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_staffrole_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['id']},
        ),
    ]
