# Generated by Django 5.2.4 on 2025-09-07 17:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectThreadReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='directthread',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='channelmember',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='channelmessage',
            index=models.Index(fields=['channel', 'timestamp', 'id'], name='idx_channel_ts_id'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['thread', 'timestamp', 'id'], name='idx_thread_ts_id'),
        ),
        migrations.AddConstraint(
            model_name='channelmember',
            constraint=models.UniqueConstraint(fields=('channel', 'user'), name='uniq_member_per_channel'),
        ),
        migrations.AddConstraint(
            model_name='directthread',
            constraint=models.CheckConstraint(condition=models.Q(('user_1', models.F('user_2')), _negated=True), name='no_self_thread'),
        ),
        migrations.AddConstraint(
            model_name='directthread',
            constraint=models.UniqueConstraint(fields=('user_1', 'user_2'), name='uniq_thread_pair'),
        ),
        migrations.AddField(
            model_name='directthreadreadstate',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='chatrooms.directthread'),
        ),
        migrations.AddField(
            model_name='directthreadreadstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_thread_read_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='directthreadreadstate',
            constraint=models.UniqueConstraint(fields=('thread', 'user'), name='uniq_readstate_per_thread_user'),
        ),
    ]
