# <<<<<<< codex/ensure-notifications-trigger-domain-actions
# # Generated by Django 5.2.4 on 2025-08-03 22:36

# import django.db.models.deletion
# from django.conf import settings
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     initial = True

#     dependencies = [
#         ("tasks", "0001_initial"),
#         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name="Notification",
#             fields=[
#                 (
#                     "id",
#                     models.BigAutoField(
#                         auto_created=True,
#                         primary_key=True,
#                         serialize=False,
#                         verbose_name="ID",
#                     ),
#                 ),
#                 ("content", models.TextField()),
#                 ("read", models.BooleanField(default=False)),
#                 ("timestamp", models.DateTimeField(auto_now_add=True)),
#                 (
#                     "level",
#                     models.CharField(
#                         choices=[
#                             ("info", "Info"),
#                             ("alert", "Alert"),
#                             ("critical", "Critical"),
#                         ],
#                         default="info",
#                         max_length=10,
#                     ),
#                 ),
#                 (
#                     "related_task",
#                     models.ForeignKey(
#                         blank=True,
#                         null=True,
#                         on_delete=django.db.models.deletion.CASCADE,
#                         related_name="notifications",
#                         to="tasks.task",
#                     ),
#                 ),
#                 (
#                     "user",
#                     models.ForeignKey(
#                         on_delete=django.db.models.deletion.CASCADE,
#                         related_name="notifications",
#                         to=settings.AUTH_USER_MODEL,
#                     ),
#                 ),
#             ],
#         ),
#     ]
# =======
# # <<<<<<< codex/implement-notification-api-components
# # # Generated by Django 5.2.4 on 2025-08-03 22:33

# # import django.db.models.deletion
# # =======
# # # Generated by Django 5.2.4 on 2025-08-03 22:34

# # import django.db.models.deletion
# # import uuid
# # >>>>>>> content
# # from django.conf import settings
# # from django.db import migrations, models


# # class Migration(migrations.Migration):

# #     initial = True

# #     dependencies = [
# #         ("contenttypes", "0002_remove_content_type_name"),
# #         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
# #     ]

# #     operations = [
# #         migrations.CreateModel(
# #             name="Notification",
# #             fields=[
# #                 (
# #                     "id",
# #                     models.BigAutoField(
# #                         auto_created=True,
# #                         primary_key=True,
# #                         serialize=False,
# #                         verbose_name="ID",
# #                     ),
# #                 ),
# # <<<<<<< codex/implement-notification-api-components
# #                 ("verb", models.CharField(max_length=255)),
# #                 ("object_id", models.PositiveIntegerField(blank=True, null=True)),
# #                 ("is_read", models.BooleanField(default=False)),
# #                 ("timestamp", models.DateTimeField(auto_now_add=True)),
# #                 (
# #                     "actor",
# #                     models.ForeignKey(
# #                         on_delete=django.db.models.deletion.CASCADE,
# #                         related_name="notifications_sent",
# #                         to=settings.AUTH_USER_MODEL,
# #                     ),
# #                 ),
# #                 (
# #                     "content_type",
# #                     models.ForeignKey(
# #                         blank=True,
# #                         null=True,
# #                         on_delete=django.db.models.deletion.CASCADE,
# #                         to="contenttypes.contenttype",
# # =======
# #                 ("created_at", models.DateTimeField(auto_now_add=True)),
# #                 ("updated_at", models.DateTimeField(auto_now=True)),
# #                 ("deleted_at", models.DateTimeField(blank=True, null=True)),
# #                 ("is_deleted", models.BooleanField(default=False)),
# #                 (
# #                     "uuid",
# #                     models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
# #                 ),
# #                 ("verb", models.CharField(max_length=255)),
# #                 (
# #                     "target_object_id",
# #                     models.PositiveIntegerField(blank=True, null=True),
# #                 ),
# #                 ("url", models.URLField(blank=True)),
# #                 ("read", models.BooleanField(default=False)),
# #                 (
# #                     "actor",
# #                     models.ForeignKey(
# #                         blank=True,
# #                         null=True,
# #                         on_delete=django.db.models.deletion.SET_NULL,
# #                         related_name="actions",
# #                         to=settings.AUTH_USER_MODEL,
# # >>>>>>> content
# #                     ),
# #                 ),
# #                 (
# #                     "recipient",
# #                     models.ForeignKey(
# #                         on_delete=django.db.models.deletion.CASCADE,
# #                         related_name="notifications",
# #                         to=settings.AUTH_USER_MODEL,
# #                     ),
# #                 ),
# # <<<<<<< codex/implement-notification-api-components
# #             ],
# #             options={
# #                 "ordering": ["-timestamp"],
# # =======
# #                 (
# #                     "target_content_type",
# #                     models.ForeignKey(
# #                         blank=True,
# #                         null=True,
# #                         on_delete=django.db.models.deletion.CASCADE,
# #                         to="contenttypes.contenttype",
# #                     ),
# #                 ),
# #             ],
# #             options={
# #                 "ordering": ["-created_at"],
# # >>>>>>> content
# #             },
# #         ),
# #     ]
# >>>>>>> content
