# Generated by Django 5.2.4 on 2025-08-03 06:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('stage', models.CharField(choices=[('prospect', 'Prospect'), ('qualified', 'Qualified'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='prospect', max_length=50)),
                ('source', models.CharField(blank=True, choices=[('field', 'Field Visit'), ('referral', 'Referral'), ('digital', 'Digital'), ('inbound', 'Inbound'), ('other', 'Other')], max_length=100)),
                ('products_discussed', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_type', models.CharField(blank=True, choices=[('call', 'Call'), ('demo', 'Demo'), ('meeting', 'Meeting'), ('install', 'Install'), ('checkin', 'Check-In')], max_length=50)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('lead_score', models.IntegerField(default=0)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=50)),
                ('documents', models.FileField(blank=True, null=True, upload_to='leads/docs/')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags like #vip,#hot', max_length=255)),
                ('assigned_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('call', 'Call'), ('demo', 'Demo'), ('meeting', 'Meeting'), ('install', 'Install'), ('checkin', 'Check-In')], max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, max_length=100)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='field.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('business_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('products_discussed', models.JSONField(blank=True, default=list)),
                ('visit_outcome', models.CharField(blank=True, choices=[('no_answer', 'No Answer'), ('refusal', 'Refusal'), ('interested', 'Interested'), ('completed', 'GPB Setup Completed'), ('sale_closed', 'Sale Closed'), ('other', 'Other')], max_length=100)),
                ('feedback_notes', models.TextField(blank=True)),
                ('follow_up_type', models.CharField(blank=True, choices=[('call', 'Call'), ('demo', 'Demo'), ('meeting', 'Meeting'), ('install', 'Install'), ('checkin', 'Check-In')], max_length=50)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('next_step_agreed', models.TextField(blank=True)),
                ('prompt_given', models.BooleanField(default=False)),
                ('customer_agreed_contact', models.BooleanField(default=True)),
                ('add_as_lead', models.BooleanField(default=False)),
                ('code_verified', models.BooleanField(default=False)),
                ('linked_lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field.lead')),
                ('rep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='field.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field.zone'),
        ),
    ]
