# Generated by Codex CLI
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(
                choices=[
                    ('new', 'New'),
                    ('interested', 'Interested'),
                    ('follow_up', 'Follow-up Scheduled'),
                    ('quote_sent', 'Quote Sent'),
                    ('closed_subscribed', 'Closed – Subscribed'),
                    ('closed_lost', 'Closed – Lost'),
                    ('on_hold', 'On Hold'),
                ],
                default='new',
                max_length=50,
            ),
        ),
    ]

