# Generated by Django 5.2.4 on 2025-09-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_lead_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-date_time', '-created_at', '-id']},
        ),
    ]
